title: DC24 Infra Dashboards

lang: ko

author:
  name: 'DC24 Infra Team'
description: >-
  DebConf24 인프라 팀은 부산에서 개최되었던 DebConf24를 지원하기 위하여 
  네트워크 회선공사, 운영, 철거에 이르는 전 과정을 수행하였습니다. 
  이 사이트는 2024년 뜨거웠던 여름을 함께 하였던 인프라 팀의 기록입니다.
  DC24 인프라 구축기와, 인프라 모니터링 시스템들을 엿보기 위한 대시보드의 스크린 캡쳐를 제공합니다.

bootstrap:
  date_format: "%b %-d, %Y"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
